/****************************************************************************
*
* Copyright © 2017-2019 STMicroelectronics - All Rights Reserved
*
* This software is licensed under SLA0098 terms that can be found in the
* DM00779817_1_0.pdf file in the licenses directory of this software product.
* 
* THIS SOFTWARE IS DISTRIBUTED "AS IS," AND ALL WARRANTIES ARE DISCLAIMED, 
* INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*
*****************************************************************************/

#ifndef _BOARD_H_
#define _BOARD_H_

#include "pal.h"

/*
 * Setup for a generic SPC58ECxx board.
 */

/*
 * Board identifiers.
 */
#define BOARD_GENERIC_SPC58ECXX
#define BOARD_NAME                  "Generic SPC58ECxx"

/*
 * Support macros.
 */
#define MSCR_IO_INDEX(port, pin)    (((port) * 16U) + (pin))

/*
 * I/O definitions.
 */
#define PIN_RXD_4                   0U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_DIS_GPIO1 1U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_FAULT_EIRQ2 10U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_BNECPOL_GPIO2 2U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_TXENCPHA_GPIO3 3U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_FREQ_GPIO4 4U
#define PIN_AEK_COM_ISOSPI1Board0_CN1_NCS0_CS0_0 11U
#define PIN_AEK_COM_ISOSPI1Board0_CN1_SDIexMOSI_MOSI_0 11U
#define PIN_AEK_COM_ISOSPI1Board0_CN1_SCKexSCK_SCK_0 4U
#define PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0 5U
#define LED3                        10U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_NSLAVE_GPIO9 14U
#define PIN_RX_4_1                  6U
#define PIN_TX_4_1                  7U
#define LED2                        8U
#define PIN_TXD_4                   15U
#define PIN_AEK_COM_ISOSPI1Board0_CN2_TXAMP_GPIO8 0U

/*
 * PORT definitions.
 */
#define PORT_PIN_RXD_4              PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_DIS_GPIO1 PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_FAULT_EIRQ2 PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_BNECPOL_GPIO2 PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_TXENCPHA_GPIO3 PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_FREQ_GPIO4 PORT_A
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_NCS0_CS0_0 PORT_B
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SDIexMOSI_MOSI_0 PORT_D
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SCKexSCK_SCK_0 PORT_D
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0 PORT_D
#define PORT_LED3                   PORT_F
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_NSLAVE_GPIO9 PORT_F
#define PORT_PIN_RX_4_1             PORT_F
#define PORT_PIN_TX_4_1             PORT_F
#define PORT_LED2                   PORT_F
#define PORT_PIN_TXD_4              PORT_G
#define PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_TXAMP_GPIO8 PORT_H

/*
 * MSCR_IO definitions.
 */
#define MSCR_IO_PIN_RXD_4           MSCR_IO_INDEX(PORT_PIN_RXD_4, PIN_RXD_4)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_DIS_GPIO1 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_DIS_GPIO1, PIN_AEK_COM_ISOSPI1Board0_CN2_DIS_GPIO1)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_FAULT_EIRQ2 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_FAULT_EIRQ2, PIN_AEK_COM_ISOSPI1Board0_CN2_FAULT_EIRQ2)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_BNECPOL_GPIO2 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_BNECPOL_GPIO2, PIN_AEK_COM_ISOSPI1Board0_CN2_BNECPOL_GPIO2)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_TXENCPHA_GPIO3 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_TXENCPHA_GPIO3, PIN_AEK_COM_ISOSPI1Board0_CN2_TXENCPHA_GPIO3)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_FREQ_GPIO4 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_FREQ_GPIO4, PIN_AEK_COM_ISOSPI1Board0_CN2_FREQ_GPIO4)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN1_NCS0_CS0_0 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_NCS0_CS0_0, PIN_AEK_COM_ISOSPI1Board0_CN1_NCS0_CS0_0)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN1_SDIexMOSI_MOSI_0 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SDIexMOSI_MOSI_0, PIN_AEK_COM_ISOSPI1Board0_CN1_SDIexMOSI_MOSI_0)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN1_SCKexSCK_SCK_0 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SCKexSCK_SCK_0, PIN_AEK_COM_ISOSPI1Board0_CN1_SCKexSCK_SCK_0)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0, PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0)
#define MSCR_IO_LED3                MSCR_IO_INDEX(PORT_LED3, LED3)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_NSLAVE_GPIO9 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_NSLAVE_GPIO9, PIN_AEK_COM_ISOSPI1Board0_CN2_NSLAVE_GPIO9)
#define MSCR_IO_PIN_RX_4_1          MSCR_IO_INDEX(PORT_PIN_RX_4_1, PIN_RX_4_1)
#define MSCR_IO_PIN_TX_4_1          MSCR_IO_INDEX(PORT_PIN_TX_4_1, PIN_TX_4_1)
#define MSCR_IO_LED2                MSCR_IO_INDEX(PORT_LED2, LED2)
#define MSCR_IO_PIN_TXD_4           MSCR_IO_INDEX(PORT_PIN_TXD_4, PIN_TXD_4)
#define MSCR_IO_PIN_AEK_COM_ISOSPI1Board0_CN2_TXAMP_GPIO8 MSCR_IO_INDEX(PORT_PIN_AEK_COM_ISOSPI1Board0_CN2_TXAMP_GPIO8, PIN_AEK_COM_ISOSPI1Board0_CN2_TXAMP_GPIO8)

/*
 * MSCR_MUX definitions.
 */
#define MSCR_MUX_PIN_RXD_4          340U
#define MSCR_MUX_PIN_AEK_COM_ISOSPI1Board0_CN1_SDOexMISO_MISO_0 368U
#define MSCR_MUX_PIN_RX_4_1         252U

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
